# General parameters
baseURL: http://localhost:1313/
languageCode: fr-FR
title: Wik-DevOps

# Theme parameters
theme: "LoveIt"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode: "en"
# language name ["English", "简体中文", "Français", "Polski", ...]
languageName: "English"

# Menu config
menu:
  main:
  - name: Posts
    weight: 1
    identifier: "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre: ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post: ""
    url: "/posts/"
    # title will be shown when you hover on this menu link
    title: ""
  - name: "Tags"  
    weight: 2
    identifier: "tags"
    pre: ""
    post: ""
    url: "/tags/"
    title: ""
  - name: "Categories"
    weight: 3
    identifier: "categories"
    pre: ""
    post: ""
    url: "/categories/"
    title: ""

# Markup related configuration in Hugo
markup:
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  markup.highlight:
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses: false